---
platform: linux

image_resource:
  type: docker-image
  source: {repository: nulldriver/cf-cli-resource, tag: "2.6.0"}

inputs:
- name: green-green-www

run:
  path: big-green-www/ci/prod-www.sh
  user: root